/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGui;

import Conexion.ConsultaGuia;
/*     */ import java.awt.EventQueue;
/*     */ import java.awt.Frame;
/*     */ import java.awt.LayoutManager;
/*     */ import java.awt.event.ActionEvent;
/*     */ import java.awt.event.ActionListener;
/*     */ import java.awt.event.FocusAdapter;
/*     */ import java.awt.event.FocusEvent;
/*     */ import java.awt.event.KeyAdapter;
/*     */ import java.awt.event.KeyEvent;
/*     */ import java.awt.event.WindowAdapter;
/*     */ import java.awt.event.WindowEvent;
/*     */ import java.sql.ResultSet;
import java.text.SimpleDateFormat;
/*     */ import java.util.ArrayList;
import java.util.Calendar;
/*     */ import java.util.logging.Level;
/*     */ import java.util.logging.Logger;
/*     */ import javax.swing.GroupLayout;
/*     */ import javax.swing.JButton;
/*     */ import javax.swing.JDialog;
/*     */ import javax.swing.JFrame;
/*     */ import javax.swing.JLabel;
/*     */ import javax.swing.JOptionPane;
/*     */ import javax.swing.JPanel;
/*     */ import javax.swing.JScrollPane;
/*     */ import javax.swing.JTable;
/*     */ import javax.swing.JTextField;
/*     */ import javax.swing.LayoutStyle;
/*     */ import javax.swing.UIManager;
/*     */ import javax.swing.UnsupportedLookAndFeelException;
/*     */ import javax.swing.border.Border;
/*     */ import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CoordTecno
 */
public class frmGuiaVotre extends JDialog {
    private static final long serialVersionUID = 1L;
    private frmImprimirGuia imprimirGuias = null;
    
    private ResultSet resGuias;
   
    private ConsultaGuia guia=null;
    private String resultado;
    protected Frame consultaparent;
   
    /**
     * Creates new form GuiaVotre
     */
    public frmGuiaVotre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Imprimir Guias Votre");
        setResizable(false);
        setBounds(100, 100, 394, 282);
        getContentPane().setLayout((LayoutManager)null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        fecInicial = new com.toedter.calendar.JDateChooser();
        fecFinal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Fecha Inicial");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Fecha Final");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Elige la fecha de captura");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        fecInicial.setDateFormatString("dd/MM/yyyy");
        fecInicial.setPreferredSize(new java.awt.Dimension(81, 25));

        fecFinal.setDateFormatString("dd/MM/yyyy");
        fecFinal.setPreferredSize(new java.awt.Dimension(81, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fecFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(fecInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(fecFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int dia=0,mes0=0,anio0=0,sumaInicial; //Extraer del Calendario Fecha Inicial
        int dia2=0,mes1=0,anio2=0,sumaFinal; //Extraer del Calendario Fecha Final
        String str;
   try{     
        String meses;
        String dias;
dia = fecInicial.getCalendar().get(Calendar.DAY_OF_MONTH);
mes0= fecInicial.getCalendar().get(Calendar.MONTH);
anio0= fecInicial.getCalendar().get(Calendar.YEAR);
sumaInicial=dia+mes0+anio0;
String fechaI;
int digitosdias = (int)(Math.log10(dia)+1);
int digitosmes = (int)(Math.log10(mes0)+1);
        if (digitosdias==1 || dia==0) {
            dias= "0"+dia;
        } else {
            dias =""+dia;
        }
        if (digitosmes==1 && mes0!=9  || mes0==0) {
            int mes=mes0+1;
            meses= "0"+mes;
        } else {
            int mes=mes0+1;
            meses =""+mes;
        }
        
fechaI = ""+ anio0+meses+dias;

//int dia2,mes1,anio2,sumaFinal; //Extraer del Calendario Fecha Final
        String meses2;
        String dias2;
dia2 = fecFinal.getCalendar().get(Calendar.DAY_OF_MONTH);
mes1= fecFinal.getCalendar().get(Calendar.MONTH);
anio2= fecFinal.getCalendar().get(Calendar.YEAR);
sumaFinal=dia2+mes1+anio2;
String fechaF;
int digitosdias2 = (int)(Math.log10(dia2)+1);
int digitosmes2 = (int)(Math.log10(mes1)+1);
        if (digitosdias2==1 || dia2==0) {
            dias2= "0"+dia2;
        } else {
            dias2 =""+dia2;
        }
        if (digitosmes2==1 && mes1!=9 || mes1==0 ) {
             int mes2=mes1+1;
            meses2= "0"+mes2;
        } else {
            int mes2=mes1+1;
            meses2 =""+mes2;
        }
        
fechaF = ""+ anio2+meses2+dias2;
 if(mes0>mes1 || anio0>anio2) {
            JOptionPane.showMessageDialog(null, "La Fecha Inicial No Puede Ser Mayor Que La Final.");
            dispose();
        }else{
        if(mes0==mes1 && dia>dia2){
            JOptionPane.showMessageDialog(null, "La Fecha Inicial No Puede Ser Mayor Que La Final.");
            dispose();
        }
 }


        
 str="or T0400009.Cod_Regional_cta = 3 and Cod_Oficina_cta=1 and cod_cuenta=1472 and Fec_captura between '"+fechaI+"' and '"+fechaF+"' and e.Cod_Regional=83";


/*     */ 
/*     */     
/* 337 */     
///* 338 */     this.resGuias = this.guia.ConsDatosGuia(str);
///*     */ 
             frmGuiaVotre.this.guia = new ConsultaGuia();
/* 123 */   frmGuiaVotre.this.resGuias = frmGuiaVotre.this.guia.ConsDatosGuia(str);
/*     */ 
/*     */     
/* 343 */     this.imprimirGuias = new frmImprimirGuia(this.consultaparent, true, this.resGuias);
/* 344 */     this.imprimirGuias.setLocationRelativeTo(null);
/* 345 */     this.imprimirGuias.setVisible(true);
/* 346 */     this.imprimirGuias.setDefaultCloseOperation(2);
/*     */     
/* 348 */     dispose();
//        System.out.println(str);
   }catch (Exception e){
       JOptionPane.showMessageDialog(null, "Por Favor Coloque Una Fecha Valida\n"+e);
   }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGuiaVotre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGuiaVotre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGuiaVotre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGuiaVotre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmGuiaVotre dialog = new frmGuiaVotre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private com.toedter.calendar.JDateChooser fecFinal;
    private com.toedter.calendar.JDateChooser fecInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
