/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGui;

import Conexion.ConsultaGuia;
/*     */ import java.awt.EventQueue;
/*     */ import java.awt.Frame;
/*     */ import java.awt.LayoutManager;
/*     */ import java.awt.event.ActionEvent;
/*     */ import java.awt.event.ActionListener;
/*     */ import java.awt.event.FocusAdapter;
/*     */ import java.awt.event.FocusEvent;
/*     */ import java.awt.event.KeyAdapter;
/*     */ import java.awt.event.KeyEvent;
/*     */ import java.awt.event.WindowAdapter;
/*     */ import java.awt.event.WindowEvent;
/*     */ import java.sql.ResultSet;
import java.text.SimpleDateFormat;
/*     */ import java.util.ArrayList;
import java.util.Calendar;
/*     */ import java.util.logging.Level;
/*     */ import java.util.logging.Logger;
/*     */ import javax.swing.GroupLayout;
/*     */ import javax.swing.JButton;
/*     */ import javax.swing.JDialog;
/*     */ import javax.swing.JFrame;
/*     */ import javax.swing.JLabel;
/*     */ import javax.swing.JOptionPane;
/*     */ import javax.swing.JPanel;
/*     */ import javax.swing.JScrollPane;
/*     */ import javax.swing.JTable;
/*     */ import javax.swing.JTextField;
/*     */ import javax.swing.LayoutStyle;
/*     */ import javax.swing.UIManager;
/*     */ import javax.swing.UnsupportedLookAndFeelException;
/*     */ import javax.swing.border.Border;
/*     */ import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CoordTecno
 */
public class frmGuiasMercadoLibre extends JDialog {
    private static final long serialVersionUID = 1L;
    private frmImprimirGuia imprimirGuias = null;
    
    private ResultSet resGuias;
   
    private ConsultaGuia guia=null;
    private String resultado;
    protected Frame consultaparent;
   
    /**
     * Creates new form GuiaVotre
     */
    public frmGuiasMercadoLibre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Imprimir Guias Mercado Libre");
        setResizable(false);
        setBounds(100, 100, 394, 282);
        getContentPane().setLayout((LayoutManager)null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNumControl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPlanilla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Imprimir guias x control de cargue o planilla");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        btnConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConsultarKeyPressed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Numero ControlC");

        txtNumControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumControlActionPerformed(evt);
            }
        });
        txtNumControl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumControlKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumControlKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Numero Planilla");

        txtPlanilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlanillaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlanillaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumControl, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtPlanilla)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jLabel3.getAccessibleContext().setAccessibleName("Imprimir guias x control de cargue o Planilla");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String control=txtNumControl.getText();  
        String planilla=txtPlanilla.getText();
        String str;
   try{     
      //JOptionPane.showMessageDialog(null, control+" o "+planilla); 

    if(control.isEmpty()==true && planilla.isEmpty()==true ){
        JOptionPane.showMessageDialog(null, "Por favor coloque un numero de control de cargue o de planilla de reparto.");
        dispose();
    }if(control.isEmpty()==true) {
        
        str="or Num_PlanillaRpto="+planilla+" and e.Cod_Regional=83 and Cod_FormaPago=4 and T0400009.ced_remitente='830067394-6'";
        }else{
         str="or Num_ControlC="+control+" and e.Cod_Regional=83 and Cod_FormaPago=4 and T0400009.ced_remitente='830067394-6'"; 
    }

///*     */ 
             frmGuiasMercadoLibre.this.guia = new ConsultaGuia();
/* 123 */   frmGuiasMercadoLibre.this.resGuias = frmGuiasMercadoLibre.this.guia.ConsDatosGuia(str);
/*     */ 
/*     */     
/* 343 */     this.imprimirGuias = new frmImprimirGuia(this.consultaparent, true, this.resGuias);
/* 344 */     this.imprimirGuias.setLocationRelativeTo(null);
/* 345 */     this.imprimirGuias.setVisible(true);
/* 346 */     this.imprimirGuias.setDefaultCloseOperation(2);
/*     */     
/* 348 */     dispose();
//        System.out.println(str);
   }catch (Exception e){
       JOptionPane.showMessageDialog(null, "Por Favor verifique los datos ingresados\n"+e);
   }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtNumControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumControlActionPerformed
        
    }//GEN-LAST:event_txtNumControlActionPerformed

    private void txtNumControlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumControlKeyTyped
        char valida = evt.getKeyChar();
         if (!Character.isDigit(valida) && evt.getKeyChar() != '' && evt.getKeyChar() != '\r' && evt
/* 376 */       .getKeyChar() != '\b' && evt.getKeyChar() != '\n' ) {
/* 377 */       getToolkit().beep();
/* 378 */       evt.consume();
/*     */     }
        int max = 5;
/* 382 */     if (this.txtNumControl.getText().length() > max && evt.getKeyChar() != '\n') {
/* 383 */       getToolkit().beep();
/* 384 */       evt.consume();
/*     */     }
    }//GEN-LAST:event_txtNumControlKeyTyped

    private void txtNumControlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumControlKeyPressed
       if (evt.getKeyCode() == 10) {
/* 273 */       this.btnConsultar.requestFocus();
/*     */     }
    }//GEN-LAST:event_txtNumControlKeyPressed

    private void btnConsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConsultarKeyPressed
       String control=txtNumControl.getText();  
        String planilla=txtPlanilla.getText();
        String str;
   try{     
      //JOptionPane.showMessageDialog(null, control+" o "+planilla); 

    if(control.isEmpty()==true && planilla.isEmpty()==true ){
        JOptionPane.showMessageDialog(null, "Por favor coloque un numero de control de cargue o de planilla de reparto.");
        dispose();
    }if(control.isEmpty()==true) {
        
        str="or Num_PlanillaRpto="+planilla+" and e.Cod_Regional=83 and Cod_FormaPago=4 and T0400009.ced_remitente='830067394-6'";
        }else{
         str="or Num_ControlC="+control+" and e.Cod_Regional=83 and Cod_FormaPago=4 and T0400009.ced_remitente='830067394-6'"; 
    }
            frmGuiasMercadoLibre.this.guia = new ConsultaGuia();
/* 123 */   frmGuiasMercadoLibre.this.resGuias = frmGuiasMercadoLibre.this.guia.ConsDatosGuia(str);     
/* 343 */     this.imprimirGuias = new frmImprimirGuia(this.consultaparent, true, this.resGuias);
/* 344 */     this.imprimirGuias.setLocationRelativeTo(null);
/* 345 */     this.imprimirGuias.setVisible(true);
/* 346 */     this.imprimirGuias.setDefaultCloseOperation(2);
/*     */     
/* 348 */     dispose();
//        
   }catch (Exception e){
       JOptionPane.showMessageDialog(null, "Por Favor verifique los datos ingresados\n"+e);
   }
    }//GEN-LAST:event_btnConsultarKeyPressed

    private void txtPlanillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlanillaKeyTyped
        char valida = evt.getKeyChar();
         if (!Character.isDigit(valida) && evt.getKeyChar() != '' && evt.getKeyChar() != '\r' && evt
/* 376 */       .getKeyChar() != '\b' && evt.getKeyChar() != '\n' ) {
/* 377 */       getToolkit().beep();
/* 378 */       evt.consume();
/*     */     }
        int max = 5;
/* 382 */     if (this.txtPlanilla.getText().length() > max && evt.getKeyChar() != '\n') {
/* 383 */       getToolkit().beep();
/* 384 */       evt.consume();
/*     */     }
    }//GEN-LAST:event_txtPlanillaKeyTyped

    private void txtPlanillaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlanillaKeyPressed
        if (evt.getKeyCode() == 10) {
/* 273 */       this.btnConsultar.requestFocus();
/*     */     }
    }//GEN-LAST:event_txtPlanillaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGuiasMercadoLibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGuiasMercadoLibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGuiasMercadoLibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGuiasMercadoLibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmGuiasMercadoLibre dialog = new frmGuiasMercadoLibre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNumControl;
    private javax.swing.JTextField txtPlanilla;
    // End of variables declaration//GEN-END:variables
}
