/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGui;

import java.awt.Frame;
import java.awt.LayoutManager;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
//import java.io.IOException;
//import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Scanner;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author CoordTecno
 */
public class StickerManual extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
    protected Frame parent;
 
    DefaultTableModel md;
    Object data [][]={};
    Object cabeza []={"Guia", "Remitente", "Destinatario", "Direccion", "Ciudad", "Unidades"};
    
   

    /**
     * Creates new form StickerManual
     */
    public StickerManual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Imprimir Sticker Manual");
        setResizable(false);
        setBounds(100, 100, 394, 282);
        getContentPane().setLayout((LayoutManager)null);
        initComponents();
        
        txtRemit.setDocument(new InterfazGui.soloMayusculas());
        txtDest.setDocument(new InterfazGui.soloMayusculas());
        txtDir.setDocument(new InterfazGui.soloMayusculas());
        txtCiud.setDocument(new InterfazGui.soloMayusculas());
        
        this.setLocationRelativeTo(this);
        
        md=new DefaultTableModel(data, cabeza);
        jTableGuia.setModel(md);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtRuta = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtGuia = new javax.swing.JTextField();
        txtRemit = new javax.swing.JTextField();
        txtDest = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        txtCiud = new javax.swing.JTextField();
        txtUnid = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGuia = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnImprimir3x11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 20));

        txtRuta.setEditable(false);

        btnSelecionar.setText("...");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jLabel10.setText("Importar Archivo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)))
        );

        jLabel2.setText("Guia");

        jLabel3.setText("Remitente");

        jLabel4.setText("Destinatario");

        jLabel5.setText("Direccion");

        jLabel6.setText("Ciudad");

        jLabel7.setText("Unidades");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addGap(4, 4, 4))
        );

        txtGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuiaActionPerformed(evt);
            }
        });
        txtGuia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGuiaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGuiaKeyTyped(evt);
            }
        });

        txtRemit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRemitKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRemitKeyTyped(evt);
            }
        });

        txtDest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDestKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDestKeyTyped(evt);
            }
        });

        txtDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDirKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirKeyTyped(evt);
            }
        });

        txtCiud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCiudKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiudKeyTyped(evt);
            }
        });

        txtUnid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnidKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRemit)
                    .addComponent(txtDest)
                    .addComponent(txtDir)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCiud, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRemit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCiud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtUnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        btnInsertar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnInsertarKeyPressed(evt);
            }
        });

        jTableGuia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Guia", "Remitente", "Destinatario", "Direccion", "Ciudad", "Unidades"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableGuia);

        btnImprimir.setText("Imp2x6");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        jLabel8.setText("Version 1.0.2");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel9.setText("By Jaramillo.");

        btnImprimir3x11.setText("Imp3X11");
        btnImprimir3x11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir3x11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnImprimir3x11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnImprimir3x11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReiniciar)
                                .addGap(41, 41, 41)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        if(archivo != null){
            txtRuta.setText(archivo.getAbsolutePath());
        }

        File file = new File(txtRuta.getText());
        //ArrayList listaGuia= new ArrayList<>();
        Scanner scanner;
        try {
            //se pasa el flujo al objeto scanner
            scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                // el objeto scanner lee linea a linea desde el archivo
                String linea = scanner.nextLine();
                Scanner delimitar = new Scanner(linea);
                //se usa una expresión regular
                //que valida que antes o despues de una TABULACION (\t) exista cualquier cosa
                //parte la cadena recibida cada vez que encuentre una TABULACION
                delimitar.useDelimiter("\t");
                Guia2 e= new Guia2(linea, linea, linea, linea,linea, 0);
                e.setGuia(delimitar.next());
                e.setRemitente(delimitar.next());
                e.setDestinatario(delimitar.next());
                e.setDir(delimitar.next());
                e.setCiudad(delimitar.next());
                e.setUnidades(delimitar.nextInt());
                //listaGuia.add(e);

                Object datos[]={e.getGuia(),e.getRemitente(),e.getDestinatario(),
                    e.getDir(),e.getCiudad(),e.getUnidades()};
                md.addRow(datos);
            }
            //se cierra el ojeto scanner
            scanner.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void txtGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuiaActionPerformed

    private void txtGuiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGuiaKeyPressed

        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtRemit.requestFocus();
        }
    }//GEN-LAST:event_txtGuiaKeyPressed

    private void txtGuiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGuiaKeyTyped
        char valida=evt.getKeyChar();

        if(!Character.isDigit(valida)&& evt.getKeyChar() != 127 && evt.getKeyChar()!= 13
            && evt.getKeyChar() != 8 && evt.getKeyChar() != 10 ){
            getToolkit().beep();
            evt.consume();
        }

        int max=11;
        if(txtGuia.getText().length()>max && evt.getKeyChar() != 10){

            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtGuiaKeyTyped

    private void txtRemitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemitKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtDest.requestFocus();
        }
    }//GEN-LAST:event_txtRemitKeyPressed

    private void txtRemitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemitKeyTyped

        int max=29;
        if(txtRemit.getText().length()>max){
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txtRemitKeyTyped

    private void txtDestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtDir.requestFocus();
        }
    }//GEN-LAST:event_txtDestKeyPressed

    private void txtDestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestKeyTyped

        int max=29;
        if(txtDest.getText().length()>max){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDestKeyTyped

    private void txtDirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtCiud.requestFocus();
        }
    }//GEN-LAST:event_txtDirKeyPressed

    private void txtDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirKeyTyped

        int max=34;
        if(txtDir.getText().length()>max){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDirKeyTyped

    private void txtCiudKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtUnid.requestFocus();
        }
    }//GEN-LAST:event_txtCiudKeyPressed

    private void txtCiudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudKeyTyped

        int max=19;
        if(txtCiud.getText().length()>max){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCiudKeyTyped

    private void txtUnidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnInsertar.requestFocus();
        }
    }//GEN-LAST:event_txtUnidKeyPressed

    private void txtUnidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidKeyTyped
        char valida=evt.getKeyChar();

        if(!Character.isDigit(valida) && evt.getKeyChar() != 127 && evt.getKeyChar() != 13
            && evt.getKeyChar() != 8 && evt.getKeyChar() != 10){
            getToolkit().beep();
            evt.consume();
        }

        int max=3;
        if(txtUnid.getText().length()>max && evt.getKeyChar() != 10){
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txtUnidKeyTyped

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        int unid = Integer.parseInt(txtUnid.getText());
        Guia2 guia=new Guia2(txtGuia.getText(),txtRemit.getText(),txtDest.getText(),
            txtDir.getText(),txtCiud.getText(),unid);
        Object datos[]={guia.getGuia(),guia.getRemitente(),guia.getDestinatario(),
            guia.getDir(),guia.getCiudad(),guia.getUnidades()};
        md.addRow(datos);

        txtGuia.setText("");
        txtRemit.setText("");
        txtDest.setText("");
        txtDir.setText("");
        txtCiud.setText("");
        txtUnid.setText("");

    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnInsertarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInsertarKeyPressed
        int unid = Integer.parseInt(txtUnid.getText());
        Guia2 guia=new Guia2(txtGuia.getText(),txtRemit.getText(),txtDest.getText(),
            txtDir.getText(),txtCiud.getText(),unid);
        Object datos[]={guia.getGuia(),guia.getRemitente(),guia.getDestinatario(),
            guia.getDir(),guia.getCiudad(),guia.getUnidades()};
        md.addRow(datos);

        txtGuia.setText("");
        txtRemit.setText("");
        txtDest.setText("");
        txtDir.setText("");
        txtCiud.setText("");
        txtUnid.setText("");

        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtGuia.requestFocus();
        }
    }//GEN-LAST:event_btnInsertarKeyPressed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        Guia2 gui;
        ArrayList <Guia2>list = new ArrayList<>();

        for (int i = 0; i < jTableGuia.getRowCount(); i++) {
            gui = new Guia2(  jTableGuia.getValueAt(i,0).toString(),
                jTableGuia.getValueAt(i,1).toString(),
                jTableGuia.getValueAt(i,2).toString(),
                jTableGuia.getValueAt(i,3).toString(),
                jTableGuia.getValueAt(i,4).toString(),
                Integer.valueOf(jTableGuia.getValueAt(i,5).toString()).intValue()

            );

            for (int j = 0; j < gui.getUnidades();j++) {
                list.add(gui);

            }
        }

        JasperReport reporte;// Instanciamos el objeto reporte
        String path = "\\\\FSERVER-CAR\\Reportes\\ReporteStickers.jasper"; //Localizacion
        try{
            reporte= (JasperReport) JRLoader.loadObjectFromFile(path);//se carga el reporte de su localizacion
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource (list));//agregamos los parametros
            //JasperViewer viewer = new JasperViewer(jprint, false); //Se crea la vista del reporte
           // viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // se declara con dispose_on_clase para que no se cierre el programa
           // viewer.setVisible(true); //se visualiza el reporte
            frmVisualRepote visualreporte = new frmVisualRepote(this.parent, true, jprint);
            visualreporte.setLocationRelativeTo(null);
            visualreporte.setVisible(true);
            visualreporte.setDefaultCloseOperation(2); 
          
        }catch (JRException e){
            e.printStackTrace();
        }
  
  
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        /*
        String gui="";
        String rem="";
        String des="";
        String di="";
        String ciu="";
        int un=0;

        Guia2 guia=new Guia2(gui,rem,des,di,ciu,un);
        Object datos[]={guia.getGuia(),guia.getRemitente(),guia.getDestinatario(),
            guia.getDir(),guia.getCiudad(),guia.getUnidades()};

        ArrayList <Guia>list = new ArrayList<>(); */
        Guia2 guiass;
        for (int i = 0; i < jTableGuia.getRowCount(); i++) {
            guiass = new Guia2(  jTableGuia.getValueAt(i,0).toString(),
                jTableGuia.getValueAt(i,1).toString(),
                jTableGuia.getValueAt(i,2).toString(),
                jTableGuia.getValueAt(i,3).toString(),
                jTableGuia.getValueAt(i,4).toString(),
                Integer.valueOf(jTableGuia.getValueAt(i,5).toString()).intValue()

            );
            md.removeRow(i);
            // list.remove(guiass);
        }

    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnImprimir3x11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir3x11ActionPerformed

        Guia2 gui;
        ArrayList <Guia2>list = new ArrayList<>();

        for (int i = 0; i < jTableGuia.getRowCount(); i++) {
            gui = new Guia2(  jTableGuia.getValueAt(i,0).toString(),
                jTableGuia.getValueAt(i,1).toString(),
                jTableGuia.getValueAt(i,2).toString(),
                jTableGuia.getValueAt(i,3).toString(),
                jTableGuia.getValueAt(i,4).toString(),
                Integer.valueOf(jTableGuia.getValueAt(i,5).toString()).intValue()

            );

            for (int j = 0; j < gui.getUnidades();j++) {
                list.add(gui);

            }
        }

        JasperReport reporte;// Instanciamos el objeto reporte
        String path = "\\\\FSERVER-CAR\\Reportes\\ReporteStikers3x11.jasper"; //Localizacion
        try{
            reporte= (JasperReport) JRLoader.loadObjectFromFile(path);//se carga el reporte de su localizacion
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource (list));//agregamos los parametros
          //  JasperViewer viewer = new JasperViewer(jprint, false); //Se crea la vista del reporte
          //  viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // se declara con dispose_on_clase para que no se cierre el programa
           // viewer.setVisible(true); //se visualiza el reporte
             frmVisualRepote visualreporte = new frmVisualRepote(this.parent, true, jprint);
            visualreporte.setLocationRelativeTo(null);
            visualreporte.setVisible(true);
            visualreporte.setDefaultCloseOperation(2);
        
        }catch (JRException e){
            e.printStackTrace();
        }
        

    }//GEN-LAST:event_btnImprimir3x11ActionPerformed

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StickerManual dialog = new StickerManual(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimir3x11;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGuia;
    private javax.swing.JTextField txtCiud;
    private javax.swing.JTextField txtDest;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtGuia;
    private javax.swing.JTextField txtRemit;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextField txtUnid;
    // End of variables declaration//GEN-END:variables
}
